USE DARKTHESTORE;
GO

-- Tắt kiểm tra khóa ngoại
EXEC sp_msforeachtable 'ALTER TABLE ? NOCHECK CONSTRAINT ALL';
GO

-- Xóa dữ liệu (bảng trung gian trước)
DELETE FROM DONHANG_SANPHAM;
DELETE FROM GIOHANG_SANPHAM;

DELETE FROM DANHGIA;
DELETE FROM DONHANG;
DELETE FROM GIOHANG;

DELETE FROM SANPHAM;
DELETE FROM DANHMUC;
DELETE FROM KHUYENMAI;
DELETE FROM QUANGCAO;
DELETE FROM KHACHHANG;

GO

-- Reset IDENTITY cho các bảng có IDENTITY
DBCC CHECKIDENT ('KHACHHANG', RESEED, 0);
DBCC CHECKIDENT ('GIOHANG', RESEED, 0);
DBCC CHECKIDENT ('DANHMUC', RESEED, 0);
DBCC CHECKIDENT ('SANPHAM', RESEED, 0);
DBCC CHECKIDENT ('DANHGIA', RESEED, 0);
DBCC CHECKIDENT ('KHUYENMAI', RESEED, 0);
DBCC CHECKIDENT ('DONHANG', RESEED, 0);
DBCC CHECKIDENT ('QUANGCAO', RESEED, 0);

GO

-- Bật lại khóa ngoại
EXEC sp_msforeachtable 'ALTER TABLE ? WITH CHECK CHECK CONSTRAINT ALL';
GO
